version: "3.9"
services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  mailserver:
    image: maildev/maildev
    ports:
      - "1080:1080"

  web:
    build: .
    tty: true
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake assets:precompile && ./bin/dev"
    volumes:
      - .:/course-rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - mailserver
    environment:
      - REDIS_URL=redis://redis:6379/
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
